
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Nov 27 08:48:30 PET 2024
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 29;
  public static final int Llave_c = 35;
  public static final int Op_booleano = 31;
  public static final int Llave_a = 34;
  public static final int P_dos = 14;
  public static final int If = 17;
  public static final int Void = 9;
  public static final int T_dato = 15;
  public static final int Static = 8;
  public static final int Clase = 7;
  public static final int Else = 18;
  public static final int Corchete_c = 37;
  public static final int Corchete_a = 36;
  public static final int While = 20;
  public static final int Division = 26;
  public static final int Cadena = 16;
  public static final int Out = 12;
  public static final int Parentesis_c = 33;
  public static final int Publico = 6;
  public static final int Signo_punto = 2;
  public static final int Parentesis_a = 32;
  public static final int For = 21;
  public static final int P_coma = 39;
  public static final int EOF = 0;
  public static final int SYSTEM = 11;
  public static final int error = 1;
  public static final int Linea = 3;
  public static final int Imprimir = 13;
  public static final int Op_atribucion = 30;
  public static final int ERROR = 42;
  public static final int Do = 19;
  public static final int Args = 10;
  public static final int Op_logico = 27;
  public static final int Paquete = 5;
  public static final int Identificador = 40;
  public static final int Resta = 24;
  public static final int Multiplicacion = 25;
  public static final int Op_incremento = 28;
  public static final int Numero = 41;
  public static final int Suma = 23;
  public static final int Main = 38;
  public static final int Igual = 22;
  public static final int Comillas = 4;
}

